// GENERATED by tools/analyze-masscode-colonization.mjs — do not edit by hand.
// Source: E:/Spansh/region-ao-master.jsonl | 1,368,676 systems with a parseable mass code | generated 2026-06-11.
// Colonization expectation + name-signature odds per mass code and per (mass code | primary class).
// goodAtmo = mean non-icy landable-atmosphere bodies; score = mean app scoreSystem total.
// p* = % of systems in the bucket with >=1: pInteresting (non-icy atmo body), pRingedBD
// (ringed brown dwarf), pOxygen (non-icy oxygen body), pBD (any brown dwarf).

export interface MassCodeStat { n: number; bodies: number; goodAtmo: number; score: number; medScore: number; pInteresting: number; pRingedBD: number; pOxygen: number; pBD: number; }

export const COLONIZATION_BY_CODE: Record<string, MassCodeStat & { landable: number; planetMass: number }> = {
  "a": {
    "n": 148334,
    "bodies": 3.47,
    "landable": 1.69,
    "goodAtmo": 0,
    "score": 2.92,
    "medScore": 0,
    "planetMass": 9.33,
    "pInteresting": 0.44,
    "pRingedBD": 0,
    "pOxygen": 0,
    "pBD": 55.41
  },
  "b": {
    "n": 699760,
    "bodies": 6,
    "landable": 2.47,
    "goodAtmo": 0.04,
    "score": 5.4,
    "medScore": 0,
    "planetMass": 94.91,
    "pInteresting": 2.47,
    "pRingedBD": 0.03,
    "pOxygen": 0.02,
    "pBD": 26.91
  },
  "c": {
    "n": 331297,
    "bodies": 7.24,
    "landable": 3.04,
    "goodAtmo": 0.16,
    "score": 9.15,
    "medScore": 0,
    "planetMass": 291.6,
    "pInteresting": 8.22,
    "pRingedBD": 0.96,
    "pOxygen": 0.04,
    "pBD": 11.94
  },
  "d": {
    "n": 186465,
    "bodies": 8.26,
    "landable": 3.51,
    "goodAtmo": 0.26,
    "score": 12.63,
    "medScore": 0,
    "planetMass": 416.06,
    "pInteresting": 11.46,
    "pRingedBD": 3.46,
    "pOxygen": 0.04,
    "pBD": 11.88
  },
  "e": {
    "n": 2814,
    "bodies": 5.42,
    "landable": 1.57,
    "goodAtmo": 0.04,
    "score": 7.9,
    "medScore": 0,
    "planetMass": 561,
    "pInteresting": 2.03,
    "pRingedBD": 2.35,
    "pOxygen": 0,
    "pBD": 3.98
  },
  "f": {
    "n": 6,
    "bodies": 1,
    "landable": 0,
    "goodAtmo": 0,
    "score": 0,
    "medScore": 0,
    "planetMass": 4.18,
    "pInteresting": 0,
    "pRingedBD": 0,
    "pOxygen": 0,
    "pBD": 0
  }
};

// Keyed "code|primaryClass" (primaryClass: O B A F G K M, BD, WD, NS, BH, WR, C, other).
export const COLONIZATION_BY_CODE_PRIMARY: Record<string, MassCodeStat & { premium: number }> = {
  "e|other": {
    "n": 1662,
    "bodies": 2.3,
    "goodAtmo": 0.01,
    "premium": 0,
    "score": 0.8,
    "medScore": 0,
    "pInteresting": 0.72,
    "pRingedBD": 0,
    "pOxygen": 0,
    "pBD": 0
  },
  "e|B": {
    "n": 792,
    "bodies": 9.57,
    "goodAtmo": 0.03,
    "premium": 0,
    "score": 19.47,
    "medScore": 12,
    "pInteresting": 1.77,
    "pRingedBD": 6.94,
    "pOxygen": 0,
    "pBD": 8.21
  },
  "e|A": {
    "n": 152,
    "bodies": 7.68,
    "goodAtmo": 0.1,
    "premium": 0,
    "score": 12.38,
    "medScore": 4,
    "pInteresting": 4.61,
    "pRingedBD": 3.95,
    "pOxygen": 0,
    "pBD": 5.92
  },
  "d|G": {
    "n": 34695,
    "bodies": 10.63,
    "goodAtmo": 0.38,
    "premium": 0.01,
    "score": 16.73,
    "medScore": 0,
    "pInteresting": 16.89,
    "pRingedBD": 4.27,
    "pOxygen": 0.1,
    "pBD": 11.62
  },
  "d|other": {
    "n": 41369,
    "bodies": 0.48,
    "goodAtmo": 0,
    "premium": 0,
    "score": 0.25,
    "medScore": 0,
    "pInteresting": 0.22,
    "pRingedBD": 0.01,
    "pOxygen": 0,
    "pBD": 0.02
  },
  "d|F": {
    "n": 64828,
    "bodies": 10.67,
    "goodAtmo": 0.39,
    "premium": 0,
    "score": 16.98,
    "medScore": 0,
    "pInteresting": 16.67,
    "pRingedBD": 5.33,
    "pOxygen": 0.06,
    "pBD": 10.65
  },
  "d|K": {
    "n": 17142,
    "bodies": 10.74,
    "goodAtmo": 0.25,
    "premium": 0.01,
    "score": 14.44,
    "medScore": 0,
    "pInteresting": 12.86,
    "pRingedBD": 2.2,
    "pOxygen": 0.03,
    "pBD": 15.45
  },
  "d|A": {
    "n": 14398,
    "bodies": 10.25,
    "goodAtmo": 0.3,
    "premium": 0.01,
    "score": 20.05,
    "medScore": 4,
    "pInteresting": 13.42,
    "pRingedBD": 7.65,
    "pOxygen": 0.03,
    "pBD": 11.38
  },
  "d|BD": {
    "n": 2927,
    "bodies": 7.65,
    "goodAtmo": 0.02,
    "premium": 0,
    "score": 7.15,
    "medScore": 0,
    "pInteresting": 1.61,
    "pRingedBD": 0.96,
    "pOxygen": 0,
    "pBD": 100
  },
  "d|M": {
    "n": 11033,
    "bodies": 9.51,
    "goodAtmo": 0.06,
    "premium": 0,
    "score": 9.18,
    "medScore": 0,
    "pInteresting": 3.81,
    "pRingedBD": 0.11,
    "pOxygen": 0.03,
    "pBD": 36.12
  },
  "c|M": {
    "n": 26578,
    "bodies": 9.17,
    "goodAtmo": 0.1,
    "premium": 0.01,
    "score": 9.53,
    "medScore": 0,
    "pInteresting": 5.54,
    "pRingedBD": 0.27,
    "pOxygen": 0.1,
    "pBD": 24.64
  },
  "c|other": {
    "n": 94608,
    "bodies": 0.66,
    "goodAtmo": 0.01,
    "premium": 0,
    "score": 0.43,
    "medScore": 0,
    "pInteresting": 0.34,
    "pRingedBD": 0,
    "pOxygen": 0,
    "pBD": 0.03
  },
  "c|K": {
    "n": 178415,
    "bodies": 9.88,
    "goodAtmo": 0.21,
    "premium": 0.01,
    "score": 12.55,
    "medScore": 0,
    "pInteresting": 11.44,
    "pRingedBD": 1.3,
    "pOxygen": 0.05,
    "pBD": 16.34
  },
  "c|G": {
    "n": 31597,
    "bodies": 10.42,
    "goodAtmo": 0.34,
    "premium": 0.01,
    "score": 15.61,
    "medScore": 0,
    "pInteresting": 15.89,
    "pRingedBD": 2.39,
    "pOxygen": 0.05,
    "pBD": 11.79
  },
  "b|M": {
    "n": 469700,
    "bodies": 8.5,
    "goodAtmo": 0.06,
    "premium": 0,
    "score": 7.74,
    "medScore": 0,
    "pInteresting": 3.53,
    "pRingedBD": 0.04,
    "pOxygen": 0.03,
    "pBD": 38.34
  },
  "b|other": {
    "n": 219107,
    "bodies": 0.52,
    "goodAtmo": 0,
    "premium": 0,
    "score": 0.26,
    "medScore": 0,
    "pInteresting": 0.15,
    "pRingedBD": 0,
    "pOxygen": 0,
    "pBD": 0.07
  },
  "b|K": {
    "n": 4028,
    "bodies": 10.27,
    "goodAtmo": 0.11,
    "premium": 0.01,
    "score": 9.94,
    "medScore": 0,
    "pInteresting": 5.69,
    "pRingedBD": 0.22,
    "pOxygen": 0.22,
    "pBD": 27.98
  },
  "b|BD": {
    "n": 6925,
    "bodies": 7.37,
    "goodAtmo": 0.03,
    "premium": 0,
    "score": 6.28,
    "medScore": 0,
    "pInteresting": 1.89,
    "pRingedBD": 0,
    "pOxygen": 0,
    "pBD": 100
  },
  "a|BD": {
    "n": 79366,
    "bodies": 5.71,
    "goodAtmo": 0.01,
    "premium": 0,
    "score": 4.88,
    "medScore": 0,
    "pInteresting": 0.64,
    "pRingedBD": 0,
    "pOxygen": 0.01,
    "pBD": 100
  },
  "a|M": {
    "n": 5995,
    "bodies": 7.57,
    "goodAtmo": 0.03,
    "premium": 0,
    "score": 6.23,
    "medScore": 0,
    "pInteresting": 2.02,
    "pRingedBD": 0,
    "pOxygen": 0,
    "pBD": 46.91
  },
  "a|other": {
    "n": 62973,
    "bodies": 0.26,
    "goodAtmo": 0,
    "premium": 0,
    "score": 0.12,
    "medScore": 0,
    "pInteresting": 0.03,
    "pRingedBD": 0,
    "pOxygen": 0,
    "pBD": 0.01
  }
};

// Galaxy-baseline rates (whole dataset) — for computing a bucket's lift vs baseline.
export const COLONIZATION_BASELINE = {
  "n": 1368676,
  "pInteresting": 4.87,
  "pRingedBD": 0.72,
  "pOxygen": 0.03,
  "pBD": 24.28
};
