// GENERATED by tools/analyze-masscode-colonization.mjs — do not edit by hand.
// Source: E:/Spansh/region-ao-master.jsonl | 1,368,676 systems with a parseable mass code | generated 2026-06-10.
// Colonization expectation per mass code and per (mass code | primary star class).
// "goodAtmo" = mean count of non-icy landable bodies with a real atmosphere; "score" = mean app scoreSystem total.

export interface MassCodeStat { n: number; bodies: number; goodAtmo: number; score: number; medScore: number; }

export const COLONIZATION_BY_CODE: Record<string, MassCodeStat & { landable: number; planetMass: number }> = {
  "a": {
    "n": 148334,
    "bodies": 3.47,
    "landable": 1.69,
    "goodAtmo": 0,
    "score": 2.92,
    "medScore": 0,
    "planetMass": 9.33
  },
  "b": {
    "n": 699760,
    "bodies": 6,
    "landable": 2.47,
    "goodAtmo": 0.04,
    "score": 5.4,
    "medScore": 0,
    "planetMass": 94.91
  },
  "c": {
    "n": 331297,
    "bodies": 7.24,
    "landable": 3.04,
    "goodAtmo": 0.16,
    "score": 9.15,
    "medScore": 0,
    "planetMass": 291.6
  },
  "d": {
    "n": 186465,
    "bodies": 8.26,
    "landable": 3.51,
    "goodAtmo": 0.26,
    "score": 12.63,
    "medScore": 0,
    "planetMass": 416.06
  },
  "e": {
    "n": 2814,
    "bodies": 5.42,
    "landable": 1.57,
    "goodAtmo": 0.04,
    "score": 7.9,
    "medScore": 0,
    "planetMass": 561
  },
  "f": {
    "n": 6,
    "bodies": 1,
    "landable": 0,
    "goodAtmo": 0,
    "score": 0,
    "medScore": 0,
    "planetMass": 4.18
  }
};

// Keyed "code|primaryClass" (primaryClass: O B A F G K M, BD, WD, NS, BH, WR, C, other).
export const COLONIZATION_BY_CODE_PRIMARY: Record<string, MassCodeStat & { premium: number; pInteresting: number }> = {
  "e|other": {
    "n": 1662,
    "bodies": 2.3,
    "goodAtmo": 0.01,
    "premium": 0,
    "pInteresting": 0,
    "score": 0.8,
    "medScore": 0
  },
  "e|B": {
    "n": 792,
    "bodies": 9.57,
    "goodAtmo": 0.03,
    "premium": 0,
    "pInteresting": 0,
    "score": 19.47,
    "medScore": 12
  },
  "e|A": {
    "n": 152,
    "bodies": 7.68,
    "goodAtmo": 0.1,
    "premium": 0,
    "pInteresting": 0,
    "score": 12.38,
    "medScore": 4
  },
  "d|G": {
    "n": 34695,
    "bodies": 10.63,
    "goodAtmo": 0.38,
    "premium": 0.01,
    "pInteresting": 0,
    "score": 16.73,
    "medScore": 0
  },
  "d|other": {
    "n": 41369,
    "bodies": 0.48,
    "goodAtmo": 0,
    "premium": 0,
    "pInteresting": 0,
    "score": 0.25,
    "medScore": 0
  },
  "d|F": {
    "n": 64828,
    "bodies": 10.67,
    "goodAtmo": 0.39,
    "premium": 0,
    "pInteresting": 0,
    "score": 16.98,
    "medScore": 0
  },
  "d|K": {
    "n": 17142,
    "bodies": 10.74,
    "goodAtmo": 0.25,
    "premium": 0.01,
    "pInteresting": 0,
    "score": 14.44,
    "medScore": 0
  },
  "d|A": {
    "n": 14398,
    "bodies": 10.25,
    "goodAtmo": 0.3,
    "premium": 0.01,
    "pInteresting": 1,
    "score": 20.05,
    "medScore": 4
  },
  "d|BD": {
    "n": 2927,
    "bodies": 7.65,
    "goodAtmo": 0.02,
    "premium": 0,
    "pInteresting": 0,
    "score": 7.15,
    "medScore": 0
  },
  "d|M": {
    "n": 11033,
    "bodies": 9.51,
    "goodAtmo": 0.06,
    "premium": 0,
    "pInteresting": 0,
    "score": 9.18,
    "medScore": 0
  },
  "c|M": {
    "n": 26578,
    "bodies": 9.17,
    "goodAtmo": 0.1,
    "premium": 0.01,
    "pInteresting": 1,
    "score": 9.53,
    "medScore": 0
  },
  "c|other": {
    "n": 94608,
    "bodies": 0.66,
    "goodAtmo": 0.01,
    "premium": 0,
    "pInteresting": 0,
    "score": 0.43,
    "medScore": 0
  },
  "c|K": {
    "n": 178415,
    "bodies": 9.88,
    "goodAtmo": 0.21,
    "premium": 0.01,
    "pInteresting": 0,
    "score": 12.55,
    "medScore": 0
  },
  "c|G": {
    "n": 31597,
    "bodies": 10.42,
    "goodAtmo": 0.34,
    "premium": 0.01,
    "pInteresting": 0,
    "score": 15.61,
    "medScore": 0
  },
  "b|M": {
    "n": 469700,
    "bodies": 8.5,
    "goodAtmo": 0.06,
    "premium": 0,
    "pInteresting": 0,
    "score": 7.74,
    "medScore": 0
  },
  "b|other": {
    "n": 219107,
    "bodies": 0.52,
    "goodAtmo": 0,
    "premium": 0,
    "pInteresting": 0,
    "score": 0.26,
    "medScore": 0
  },
  "b|K": {
    "n": 4028,
    "bodies": 10.27,
    "goodAtmo": 0.11,
    "premium": 0.01,
    "pInteresting": 1,
    "score": 9.94,
    "medScore": 0
  },
  "b|BD": {
    "n": 6925,
    "bodies": 7.37,
    "goodAtmo": 0.03,
    "premium": 0,
    "pInteresting": 0,
    "score": 6.28,
    "medScore": 0
  },
  "a|BD": {
    "n": 79366,
    "bodies": 5.71,
    "goodAtmo": 0.01,
    "premium": 0,
    "pInteresting": 0,
    "score": 4.88,
    "medScore": 0
  },
  "a|M": {
    "n": 5995,
    "bodies": 7.57,
    "goodAtmo": 0.03,
    "premium": 0,
    "pInteresting": 0,
    "score": 6.23,
    "medScore": 0
  },
  "a|other": {
    "n": 62973,
    "bodies": 0.26,
    "goodAtmo": 0,
    "premium": 0,
    "pInteresting": 0,
    "score": 0.12,
    "medScore": 0
  }
};
