/**
 * AUTO-GENERATED by tools/build-wiki-commodity-map.mjs — do not edit by hand.
 *
 * Source: Elite Dangerous Fandom wiki — Commodities & Commodities/Supply_and_Demand.
 *
 * Each entry maps a commodity display name (wiki canonical) to:
 *   - category: the wiki category heading (Foods, Machinery, etc.)
 *   - suppliedBy: economies whose stations PRODUCE this commodity (S marks)
 *   - demandedBy: economies whose stations CONSUME this commodity (D marks)
 *
 * Generated: 2026-05-27T05:37:38.680Z
 */

export type WikiEconomy =
  | 'Extraction'
  | 'Refinery'
  | 'Agriculture'
  | 'Industrial'
  | 'HighTech'
  | 'Terraforming'
  | 'Tourism'
  | 'Military'
  | 'Service';

export interface WikiCommodityEntry {
  category: string;
  suppliedBy: WikiEconomy[];
  demandedBy: WikiEconomy[];
}

export const WIKI_COMMODITIES: Record<string, WikiCommodityEntry> = {

  // === Chemicals ===
  'Explosives': { category: 'Chemicals', suppliedBy: ['Refinery'], demandedBy: ['Extraction'] },
  'Hydrogen Fuel': { category: 'Chemicals', suppliedBy: ['Extraction', 'Refinery', 'Agriculture', 'Industrial', 'HighTech', 'Terraforming', 'Tourism', 'Military', 'Service'], demandedBy: [] },
  'Mineral Oil': { category: 'Chemicals', suppliedBy: ['Agriculture'], demandedBy: ['Refinery'] },
  'Pesticides': { category: 'Chemicals', suppliedBy: ['HighTech'], demandedBy: ['Agriculture'] },

  // === Consumer Items ===
  'Clothing': { category: 'Consumer Items', suppliedBy: ['Industrial'], demandedBy: ['Extraction', 'Refinery', 'Agriculture', 'HighTech', 'Terraforming', 'Tourism'] },
  'Consumer Technology': { category: 'Consumer Items', suppliedBy: ['HighTech'], demandedBy: ['Extraction', 'Refinery', 'Agriculture', 'Industrial', 'Terraforming', 'Tourism'] },
  'Domestic Appliances': { category: 'Consumer Items', suppliedBy: ['Industrial'], demandedBy: ['Extraction', 'Refinery', 'Agriculture', 'HighTech', 'Terraforming', 'Tourism'] },

  // === Drugs ===
  'Beer': { category: 'Drugs', suppliedBy: ['Agriculture'], demandedBy: ['Refinery', 'HighTech', 'Tourism'] },
  'Liquor': { category: 'Drugs', suppliedBy: ['Agriculture', 'Industrial'], demandedBy: ['Extraction', 'Terraforming', 'Tourism'] },
  'Narcotics': { category: 'Drugs', suppliedBy: [], demandedBy: [] },
  'Tobacco': { category: 'Drugs', suppliedBy: ['Agriculture'], demandedBy: ['Extraction', 'Terraforming', 'Tourism'] },
  'Wine': { category: 'Drugs', suppliedBy: ['Agriculture'], demandedBy: ['Extraction', 'Industrial', 'Terraforming', 'Tourism'] },

  // === Foods ===
  'Algae': { category: 'Foods', suppliedBy: ['Agriculture'], demandedBy: ['Industrial'] },
  'Animal Meat': { category: 'Foods', suppliedBy: ['Agriculture'], demandedBy: ['Extraction', 'Refinery', 'Industrial', 'HighTech', 'Terraforming', 'Tourism'] },
  'Coffee': { category: 'Foods', suppliedBy: ['Agriculture'], demandedBy: ['Extraction', 'Refinery', 'Industrial', 'HighTech', 'Terraforming', 'Tourism'] },
  'Fish': { category: 'Foods', suppliedBy: ['Agriculture'], demandedBy: ['Extraction', 'Refinery', 'Industrial', 'HighTech', 'Terraforming', 'Tourism'] },
  'Food Cartridges': { category: 'Foods', suppliedBy: ['Industrial'], demandedBy: ['Extraction', 'Refinery', 'HighTech', 'Terraforming', 'Tourism'] },
  'Fruit and Vegetables': { category: 'Foods', suppliedBy: ['Agriculture'], demandedBy: ['Extraction', 'Refinery', 'Industrial', 'HighTech', 'Terraforming', 'Tourism'] },
  'Grain': { category: 'Foods', suppliedBy: ['Agriculture'], demandedBy: ['Extraction', 'Refinery', 'Industrial', 'HighTech', 'Terraforming', 'Tourism'] },
  'Synthetic Meat': { category: 'Foods', suppliedBy: ['HighTech'], demandedBy: ['Extraction', 'Refinery', 'Industrial', 'Terraforming', 'Tourism'] },
  'Tea': { category: 'Foods', suppliedBy: ['Agriculture'], demandedBy: ['Extraction', 'Refinery', 'Industrial', 'HighTech', 'Terraforming', 'Tourism'] },

  // === Industrial Materials ===
  'Insulating Membrane': { category: 'Industrial Materials', suppliedBy: ['Refinery'], demandedBy: ['Industrial', 'HighTech', 'Military'] },
  'Polymers': { category: 'Industrial Materials', suppliedBy: ['Refinery'], demandedBy: ['Industrial', 'Terraforming'] },
  'Semiconductors': { category: 'Industrial Materials', suppliedBy: ['Refinery'], demandedBy: ['Industrial', 'Terraforming'] },
  'Superconductors': { category: 'Industrial Materials', suppliedBy: ['Refinery'], demandedBy: ['Industrial', 'HighTech', 'Terraforming'] },

  // === Machinery ===
  'Atmospheric Processors': { category: 'Machinery', suppliedBy: ['Industrial'], demandedBy: ['Agriculture', 'Terraforming'] },
  'Crop Harvesters': { category: 'Machinery', suppliedBy: ['Industrial'], demandedBy: ['Agriculture'] },
  'Marine Equipment': { category: 'Machinery', suppliedBy: ['Industrial'], demandedBy: ['Agriculture'] },
  'Microbial Furnaces': { category: 'Machinery', suppliedBy: ['HighTech'], demandedBy: ['Refinery'] },
  'Mineral Extractors': { category: 'Machinery', suppliedBy: ['Industrial'], demandedBy: ['Extraction'] },
  'Power Generators': { category: 'Machinery', suppliedBy: ['Industrial'], demandedBy: ['Extraction', 'Agriculture', 'Terraforming', 'Tourism'] },
  'Water Purifiers': { category: 'Machinery', suppliedBy: ['Industrial'], demandedBy: ['Extraction', 'Agriculture', 'Terraforming', 'Tourism'] },

  // === Medicines ===
  'Agri-Medicines': { category: 'Medicines', suppliedBy: ['HighTech'], demandedBy: ['Agriculture'] },
  'Basic Medicines': { category: 'Medicines', suppliedBy: ['Industrial', 'HighTech'], demandedBy: ['Extraction', 'Refinery', 'Agriculture', 'Terraforming', 'Tourism'] },
  'Combat Stabilisers': { category: 'Medicines', suppliedBy: ['HighTech'], demandedBy: [] },
  'Performance Enhancers': { category: 'Medicines', suppliedBy: ['HighTech'], demandedBy: ['Extraction', 'Agriculture', 'Industrial'] },
  'Progenitor Cells': { category: 'Medicines', suppliedBy: ['HighTech'], demandedBy: ['Extraction', 'Refinery', 'Agriculture', 'Industrial', 'Terraforming', 'Tourism'] },

  // === Metals ===
  'Aluminium': { category: 'Metals', suppliedBy: ['Refinery'], demandedBy: ['Industrial'] },
  'Beryllium': { category: 'Metals', suppliedBy: ['Refinery'], demandedBy: ['Industrial'] },
  'Cobalt': { category: 'Metals', suppliedBy: ['Extraction'], demandedBy: ['Industrial'] },
  'Copper': { category: 'Metals', suppliedBy: ['Refinery'], demandedBy: ['Industrial'] },
  'Gallium': { category: 'Metals', suppliedBy: ['Refinery'], demandedBy: ['Industrial'] },
  'Gold': { category: 'Metals', suppliedBy: ['Extraction'], demandedBy: ['Industrial', 'HighTech', 'Terraforming', 'Tourism'] },
  'Indium': { category: 'Metals', suppliedBy: ['Refinery'], demandedBy: ['Industrial', 'HighTech'] },
  'Lithium': { category: 'Metals', suppliedBy: ['Refinery'], demandedBy: ['Industrial', 'HighTech'] },
  'Palladium': { category: 'Metals', suppliedBy: ['Extraction'], demandedBy: ['Industrial', 'HighTech', 'Terraforming', 'Tourism'] },
  'Platinum': { category: 'Metals', suppliedBy: [], demandedBy: ['Industrial', 'Terraforming', 'Tourism'] },
  'Silver': { category: 'Metals', suppliedBy: ['Extraction'], demandedBy: ['Industrial', 'HighTech', 'Terraforming', 'Tourism'] },
  'Tantalum': { category: 'Metals', suppliedBy: ['Refinery'], demandedBy: ['Industrial', 'HighTech'] },
  'Titanium': { category: 'Metals', suppliedBy: ['Refinery'], demandedBy: ['Industrial', 'HighTech'] },
  'Uranium': { category: 'Metals', suppliedBy: ['Refinery'], demandedBy: ['Industrial', 'HighTech'] },

  // === Minerals ===
  'Bauxite': { category: 'Minerals', suppliedBy: ['Extraction'], demandedBy: ['Refinery'] },
  'Bertrandite': { category: 'Minerals', suppliedBy: ['Extraction'], demandedBy: ['Refinery'] },
  'Coltan': { category: 'Minerals', suppliedBy: ['Extraction'], demandedBy: ['Refinery'] },
  'Gallite': { category: 'Minerals', suppliedBy: ['Extraction'], demandedBy: ['Refinery', 'HighTech'] },
  'Indite': { category: 'Minerals', suppliedBy: ['Extraction'], demandedBy: ['Refinery'] },
  'Lepidolite': { category: 'Minerals', suppliedBy: ['Extraction', 'Refinery'], demandedBy: ['HighTech'] },
  'Rutile': { category: 'Minerals', suppliedBy: ['Extraction'], demandedBy: ['Refinery'] },
  'Uraninite': { category: 'Minerals', suppliedBy: ['Extraction'], demandedBy: ['Refinery'] },

  // === Slavery ===
  'Imperial Slaves': { category: 'Slavery', suppliedBy: [], demandedBy: [] },
  'Slaves': { category: 'Slavery', suppliedBy: [], demandedBy: [] },

  // === Technology ===
  'Advanced Catalysers': { category: 'Technology', suppliedBy: ['HighTech'], demandedBy: ['Refinery'] },
  'Animal Monitors': { category: 'Technology', suppliedBy: ['HighTech'], demandedBy: ['Agriculture'] },
  'Aquaponic Systems': { category: 'Technology', suppliedBy: ['HighTech'], demandedBy: ['Agriculture', 'Terraforming'] },
  'Auto Fabricators': { category: 'Technology', suppliedBy: ['HighTech'], demandedBy: ['Industrial', 'Terraforming'] },
  'Bioreducing Lichen': { category: 'Technology', suppliedBy: ['HighTech'], demandedBy: ['Extraction'] },
  'Computer Components': { category: 'Technology', suppliedBy: [], demandedBy: ['Industrial', 'HighTech'] },
  'H.E. Suits': { category: 'Technology', suppliedBy: ['HighTech'], demandedBy: ['Extraction', 'Refinery', 'Industrial', 'Terraforming'] },
  'Land Enrichment Systems': { category: 'Technology', suppliedBy: ['HighTech'], demandedBy: ['Agriculture', 'Terraforming'] },
  'Micro Controllers': { category: 'Technology', suppliedBy: ['HighTech'], demandedBy: ['Industrial', 'Military'] },
  'Resonating Separators': { category: 'Technology', suppliedBy: ['HighTech'], demandedBy: ['Refinery'] },
  'Robotics': { category: 'Technology', suppliedBy: ['HighTech'], demandedBy: ['Industrial'] },

  // === Textiles ===
  'Leather': { category: 'Textiles', suppliedBy: ['Agriculture'], demandedBy: ['Industrial'] },
  'Natural Fabrics': { category: 'Textiles', suppliedBy: ['Agriculture'], demandedBy: ['Industrial'] },
  'Synthetic Fabrics': { category: 'Textiles', suppliedBy: ['Refinery'], demandedBy: ['Industrial', 'Terraforming'] },

  // === Waste ===
  'Biowaste': { category: 'Waste', suppliedBy: ['Extraction', 'Refinery', 'Industrial', 'HighTech', 'Terraforming', 'Tourism'], demandedBy: ['Agriculture'] },
  'Chemical Waste': { category: 'Waste', suppliedBy: [], demandedBy: [] },
  'Scrap': { category: 'Waste', suppliedBy: ['Industrial', 'HighTech'], demandedBy: ['Refinery'] },

  // === Weapons ===
  'Battle Weapons': { category: 'Weapons', suppliedBy: [], demandedBy: [] },
  'Non-Lethal Weapons': { category: 'Weapons', suppliedBy: ['HighTech'], demandedBy: ['Extraction', 'Refinery', 'Agriculture', 'Industrial', 'Terraforming', 'Tourism'] },
  'Personal Weapons': { category: 'Weapons', suppliedBy: [], demandedBy: [] },
  'Reactive Armour': { category: 'Weapons', suppliedBy: ['HighTech'], demandedBy: ['Extraction', 'Agriculture', 'Industrial', 'Terraforming', 'Tourism'] },
};

export const WIKI_CATEGORIES: { name: string; description: string }[] = [
  { name: 'Chemicals', description: 'Chemicals are a class of natural and synthetic compounds that have a variety of industrial, agricultural, and scientific applications.' },
  { name: 'Consumer Items', description: 'Consumer Items are those materials and items specifically created for human comfort and basic survival.' },
  { name: 'Foods', description: 'Foods are organic products harvested from flora and fauna for human consumption.' },
  { name: 'Industrial Materials', description: 'Industrial Materials are refined products used in the manufacture of machinery, ships, and structures.' },
  { name: 'Legal Drugs', description: 'Legal Drugs are substances that alter the mind and body, and can be legally traded at most markets.' },
  { name: 'Machinery', description: 'Machinery supports a wide variety of important functions, from producing clean water to providing power to regulating heat output.' },
  { name: 'Medicines', description: 'Medicines are substances and compounds used to treat illnesses in humans and enhance overall health.' },
  { name: 'Metals', description: 'Metals are malleable and ductile substances that are vitally important to the manufacture of everything from electronics to ship hulls.' },
  { name: 'Minerals', description: 'Minerals are chemical compounds that are mined from naturally-occurring deposits and can be refined into other substances. Some minerals are prized as precious gemstones and can fetch a high price at most markets.' },
  { name: 'Salvage', description: 'Salvage items are generally obtained by a [[salvager]] or [[pirate]] from sites containing preexisting wreckage, abandoned structures, or alien structures. Salvage is usually marked [[Stolen Goods|stolen]] or [[Illegal Goods|illegal]] in most systems. Certain Salvage items, such as Escape Pods and Black Boxes, can be given to the Search & Rescue Contact available at most Stations.' },
  { name: 'Slavery', description: 'Slaves are beings forced into labor and servitude, usually against their will and with no compensation or legal protections. Conventional slavery is illegal in most systems other than Anarchies, but [[Imperial Slavery]], a regulated form of indentured servitude, is legal in the [[Empire]] and heavily integrated into its culture.' },
  { name: 'Technology', description: 'Technology Commodities are tools, mechanisms, and materials with significant complexity and highly-specialised applications. They drive the colonisation of new systems, the enrichment of existing habitation centres, and the advancement of science.' },
  { name: 'Textiles', description: 'Textiles are materials made of interlacing fibres. They are primarily used in the manufacture of clothing and furnishings.' },
  { name: 'Waste', description: 'Waste is material generated through the consumption of other materials. While some Waste Commodities can be re-used in other applications, others are too volatile and hazardous and require proper disposal.' },
  { name: 'Weapons', description: 'Weapons are tools designed and utilised for combat and defensive purposes. Their trade is strictly regulated in most systems.' },
];
