// AUTO-GENERATED by tools/promote-copilot-captures.mjs from rated LIVE captures.
// Promoted templates served free at runtime before live generation. Safe to delete to reset.
// Shape mirrors copilotCannedData.js: { [persona]: { [beatKey]: ["...{slot}..."] } }.

export default {
 "wash": {
  "night-vision": [
   "Everything's gone deep-green and spooky. That's the face of someone who doesn't plan on stopping till the work's done."
  ],
  "flight-assist": [
   "No safety net now. I'm white-knuckling the armrest and trying *real hard* not to drive from the right seat."
  ]
 },
 "tars": {
  "pips-shields": [
   "Full shields over your own turf — you don't swap engine-priority without cause. Either scan's showing something or you know something I don't."
  ]
 }
};
